# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f67d02fb12ece8588dd5b9bfc7f637c42c01261c1954642c5e8aea9d78a661a64823265976f6db4a5296ee22a2d14eea6a03eb4d50177572cea4c86c7adbd624

test:
  secret_key_base: 79d6552169469067f66f3e37f6bc56a8e867f2f6d7084c8d5a89b71f8d51bd5302b2f5e1a166b52d7ea2ae3601b963b49962cfa444ebef4ddaa7aacb7a870369

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
